In [2]:
import torch

def describe(x):
    print("Type: {}".format(x.type())) 
    print("Shape/size: {}".format(x.shape)) 
    print("Values: \n{}".format(x))

describe(torch.Tensor(2, 3))
describe(torch.rand(2, 3)) # uniform random 
describe(torch.randn(2, 3)) # random normal
describe(torch.zeros(2, 3)) 
x = torch.ones(2, 3)
describe(x)
x.fill_(5)
describe(x)
x = torch.Tensor([[1, 2, 3], [4, 5, 6]])
describe(x)



Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.5331, 0.6193, 0.9455],
        [0.6614, 0.2742, 0.8775]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[-0.4978,  0.1484, -1.0333],
        [ 1.8324,  0.2844, -0.7934]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [3]:
'''Creating and initializing a tensor from NumPy'''
import torch
import numpy as np

npy = np.random.rand(2, 3) 
describe(torch.from_numpy(npy))

Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.9793, 0.2635, 0.3863],
        [0.2995, 0.3770, 0.4928]], dtype=torch.float64)


In [4]:
'''Tensor Types and Size'''
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
describe(x)
x = x.long() 
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [13]:
'''Tensor Operations'''
x = torch.randn(2, 3) 
describe(x)
describe(torch.add(x, x))
describe(x + x)
x = torch.arange(6) 
describe(x)
x = x.view(2, 3) 
describe(x)
describe(torch.sum(x, dim=0))
describe(torch.sum(x, dim=1))
describe(torch.transpose(x, 0, 1))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.1994,  1.1253,  0.7844],
        [ 1.3021, -1.0265,  0.2363]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.3988,  2.2506,  1.5688],
        [ 2.6042, -2.0530,  0.4725]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.3988,  2.2506,  1.5688],
        [ 2.6042, -2.0530,  0.4725]])
Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])
Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: 
tensor([3, 5, 7])
Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([ 3, 12])
Type: torch.LongTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [7]:
'''Indexing, Slicing, and Joining'''
x = torch.arange(6).view(2, 3) 
describe(x)
describe(x[:1, :2])
describe(x[:2, :2])
describe(x[0, 1])

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([1, 2])
Values: 
tensor([[0, 1]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[0, 1],
        [3, 4]])
Type: torch.LongTensor
Shape/size: torch.Size([])
Values: 
1


In [10]:
indices = torch.LongTensor([0, 2])
describe(x)
describe(torch.index_select(x, dim=1, index=indices))
indices = torch.LongTensor([0, 0]) 
describe(torch.index_select(x, dim=0, index=indices))
row_indices = torch.arange(2).long() 
col_indices = torch.LongTensor([0, 1]) 
describe(x[row_indices, col_indices])

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[0, 2],
        [3, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [0, 1, 2]])
Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([0, 4])


In [13]:
'''Concatenate. Tensors'''
describe(x)
describe(torch.cat([x,x]))
describe(torch.cat([x,x],dim=0))
describe(torch.cat([x,x],dim=1))
describe(torch.stack([x, x]))

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [23]:
'''Multiplication'''
x1 = torch.arange(6).view(2, 3) 
describe(x1)
x2 = torch.ones(3, 2) 
describe(x2[:, 1])

x2[:, 1] += 1
describe(x2)
describe(torch.mm(x1, x2.long()))

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
Type: torch.FloatTensor
Shape/size: torch.Size([3])
Values: 
tensor([1., 1., 1.])
Type: torch.FloatTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[ 3,  6],
        [12, 24]])


In [27]:
''' Computational Graphs'''
x = torch.ones(2, 2, requires_grad=True) 
describe(x)
print(x.grad is None)
y = (x + 2) * (x + 5) + 3 
describe(y)
print(x.grad is None)
z = y.mean() 
describe(z) 
z.backward() 
print(x.grad is None)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True
Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
True
Type: torch.FloatTensor
Shape/size: torch.Size([])
Values: 
21.0
False


In [1]:
import torch
class RankAxesShape():
    def __init__(self):
        self.dd = [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]
        ]

    def rank_of_tensor(self):
        """
        A tensor's rank tells us how many indexes are needed to refer to a specific element within the tensor,
        the number of dimensions present within the tensor
        """
        print(self.dd[0][0])
        print("Rank 2")

    def axes_of_tensor(self):
        """
        An axis of a tensor is a specific dimension of a tensor.The length of each axis tells us
        how many indexes are available along each axis.
        """
        print("Each element along the first axis, is an array: ")
        print(self.dd[0])
        print(self.dd[1])
        print(self.dd[2])
        print("Each element along the second axis, is a number: ")
        print(self.dd[0][0])
        print(self.dd[1][0])
        print(self.dd[2][1])

    def shape_of_tensor(self):
        """The shape of a tensor gives us the length of each axis of the tensor. """
        print(torch.tensor(self.dd).shape)

s = RankAxesShape()
s.rank_of_tensor()
s.axes_of_tensor()
s.shape_of_tensor()

1
Rank 2
Each element along the first axis, is an array: 
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
Each element along the second axis, is a number: 
1
4
8
torch.Size([3, 3])
