In [4]:
import torch

def describe(x):
    print("Type: {}".format(x.type())) 
    print("Shape/size: {}".format(x.shape)) 
    print("Values: \n{}".format(x))

describe(torch.Tensor(2, 3))
describe(torch.rand(2, 3)) # uniform random 
describe(torch.randn(2, 3)) # random normal
describe(torch.zeros(2, 3)) 
x = torch.ones(2, 3)
describe(x)
x.fill_(5)
describe(x)
x = torch.Tensor([[1, 2, 3], [4, 5, 6]])
describe(x)



Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[4.7541e-23, 1.4013e-45,        nan],
        [5.0000e+00, 1.4013e-45, 0.0000e+00]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.5257, 0.6302, 0.1379],
        [0.7894, 0.4679, 0.6650]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[-0.0981, -2.0107,  1.9353],
        [-0.9266,  1.1781,  0.4401]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [5]:
'''Creating and initializing a tensor from NumPy'''
import torch
import numpy as np

npy = np.random.rand(2, 3) 
describe(torch.from_numpy(npy))

Type: torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.7370, 0.6038, 0.9094],
        [0.9779, 0.0650, 0.5372]], dtype=torch.float64)


In [7]:
'''Tensor Types and Size'''
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
describe(x)
x = x.long() 
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [13]:
'''Tensor Operations'''
x = torch.randn(2, 3) 
describe(x)
describe(torch.add(x, x))
describe(x + x)
x = torch.arange(6) 
describe(x)
x = x.view(2, 3) 
describe(x)
describe(torch.sum(x, dim=0))
describe(torch.sum(x, dim=1))
describe(torch.transpose(x, 0, 1))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.1994,  1.1253,  0.7844],
        [ 1.3021, -1.0265,  0.2363]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.3988,  2.2506,  1.5688],
        [ 2.6042, -2.0530,  0.4725]])
Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 0.3988,  2.2506,  1.5688],
        [ 2.6042, -2.0530,  0.4725]])
Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])
Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: 
tensor([3, 5, 7])
Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([ 3, 12])
Type: torch.LongTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [20]:
'''Indexing, Slicing, and Joining'''
x = torch.arange(6).view(2, 3) 
describe(x)
describe(x[:1, :2])
describe(x[:2, :2])
describe(x[0, 1])

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/size: torch.Size([1, 2])
Values: 
tensor([[0, 1]])
Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[0, 1],
        [3, 4]])
Type: torch.LongTensor
Shape/size: torch.Size([])
Values: 
1
